version: "3.9"
services:
  postgres:
    image: ankane/pgvector:latest
    container_name: pgvector-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: vedai
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data